name: Deploy no Render
on:
  push:
    branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout do codigo fonte
              uses: actions/checkout@v4
            - name: Configurar JDK 17
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribuition: 'temurin'
            - name: Rodar testes do Maven
              working-directory: ./backend
              run: mvn clean verify
            - name: Acionar deploy hook do Render
              run: curl "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
